### ISSUE TITLE
[BUG]这个位置在协同编辑的时候会报错. 

### ISSUE THREAD

**Issue by HengCC** [dream-num/Luckysheet#1039]
https://github.com/mengshukeji/Luckysheet/blob/56b93abb0fd8bf2e5b1dea71694d686c959ab247/src/controllers/server.js#L258

实际值
![image](https://user-images.githubusercontent.com/6167532/171100500-630927df-ea9c-4f66-8223-4e4d6207c7a6.png)
item2.range[0]一直为undefined的. 所以下面的代码提示正在输出的状态的代码就不会触发

**Comment by xiaoliuzi955** [comment]
遇到了同样的问题，兄弟解决了吗

**Comment by HengCC** [comment]
修改取值方式就行了. 
原先的
```js
val.v = item.v[0] || item.range[0]
```
判断item类型. 取item.v[0] || item?.v?.range[0]
