### ISSUE TITLE
单元格编辑状态，复制粘贴到其他单元格字号会变大

### ISSUE THREAD

**Issue by WJWM0316** [dream-num/Luckysheet#108]
我双击单元格， 进入编辑状态在复制，再双击其他单元格，进入编辑状态再粘贴。 字体就变大了。 看了下html， 变大的字体被一个span标签包裹着 且设置了一个字号，应该是计算出来的字号。demo 里有样式的单元格按照这种方式 可以100%复现。
![image](https://user-images.githubusercontent.com/24445802/96681465-e35f3380-13a9-11eb-82f5-9baee549ec41.png)

**Comment by Dushusir** [comment]
fix by https://github.com/dream-num/Luckysheet/commit/c8dd4240166be026b5c4b78538509fdb1a97ee34
