### ISSUE TITLE
delete数据时网页崩溃

### ISSUE THREAD

**Issue by WJWM0316** [dream-num/Luckysheet#109]
选择多行数据，批量删除时会出现页面崩溃的情况。谷歌浏览器

**Comment by mengshukeji** [comment]
帮忙提供具体的数据或者操作演示

**Comment by Dushusir** [comment]
没有具体数据。请提供复现的操作步骤，重新提交issue。

No specific data. Please provide the steps to reproduce and resubmit the issue
