### ISSUE TITLE
拖拽复制粘贴几十行会导致浏览器崩溃

### ISSUE THREAD

**Issue by WJWM0316** [dream-num/Luckysheet#110]
选择几十行数据， 然后进行拖拽或者 复制粘贴操作 都会 导致浏览器崩溃

**Comment by mengshukeji** [comment]
是否有具体的数据可以提供？或者操作演示

**Comment by Dushusir** [comment]
没有具体数据，待复现后重新提交可复现的操作步骤

There is no specific data, and resubmit the reproducible operation steps after it is reproduced
