### ISSUE TITLE
现在是任何PR都合并的么？

### ISSUE THREAD

**Issue by cdswyda** [dream-num/Luckysheet#1126]
刚同步了官方仓库的主分支，发现一个很严重的错误。

#977  这个PR，一次修改了22个文件，变动是 `$("body")` 变成了 `$("body").first()`

如下图：

![image](https://user-images.githubusercontent.com/13060680/185021098-b2b924f3-ec15-463f-b7d3-ff392ce97bbc.png)

这个改动一言难尽，怎么会有多个 body 标签呢？一个开源库没必要给非正常的使用买单修改吧。

**Comment by luncheon** [comment]
How about sending a PR to revert?

**Comment by HengCC** [comment]
你看这个位置也是https://github.com/mengshukeji/Luckysheet/blob/3527d280e12140d1ab4d634c4aa62b2fb7ab9a42/src/controllers/server.js#L218-L229

不太懂这么做的意义. 如果你们用了协同编辑 会发现这里也会各种undefined错.  原本type=1就是无意义的一个ack. 客户端还需要做什么处理呢?? 这段删代码原先也是没有的. 后来被PR进去的.

**Comment by nekobc1998923** [comment]
多个body标签是什么操作

**Comment by dream-num** [comment]
非常感谢发现我们的不足。之后合并PR时会多加省察。

Thank you very much for spotting our shortcomings. Later, when merging PRs, we will check more.
