### ISSUE TITLE
[BUG] Formula calculation never updated

### ISSUE THREAD

**Issue by efrancedev** [dream-num/Luckysheet#1174]
**After loading a sheet with formula, the pre-existing formulas are never updated **

1. I am loading a sheet with some data and an existing formula (eg basic sum)
2. When I change a cell value, related formula is never updated

Can check the code here :

https://codepen.io/pyksycom/pen/zYjjgOv

In this example, if I change A1 or A2 value, A3 is never updated.

Also, I have tried with assigning options.data or using loadData and a json file and the result is the same.

Haven't figured out what I'm doing wrong

**Comment by luncheon** [comment]
This is not an official answer, but I think this will solve the problem.

```js
window.sheetFormula = {
  ...
  "calcChain": [
    // r: row index, c: column index, index: sheet index
    { r: 2, c: 0, index: "1" },
  ],
}
```
https://codepen.io/luncheon/pen/eYrKYzQ

**Comment by efrancedev** [comment]
Thank you very much, that solves it.
When I back up sheet data in my database, I added instructions to detect if there is a formula and generate calcChain. There is probably a better way but anyway now it's working.
Thanks a lot ;)

**Comment by 98rahul** [comment]
> Thank you very much, that solves it. When I back up sheet data in my database, I added instructions to detect if there is a formula and generate calcChain. There is probably a better way but anyway now it's working. Thanks a lot ;)

It didn't worked as also take the codepen referance.. the issue triggered.
any codesnippets work-around would be more helpful
[ref.](https://github.com/dream-num/Luckysheet/issues/1273#issue-1633689281)
