### ISSUE TITLE
[BUG]两个bug

### ISSUE THREAD

**Issue by lxhlxh520** [dream-num/Luckysheet#1212]
①开启协同功能后,前端websokcet发给后端的数据无法用pako解压报,报头错误,,,我下断点拦截压缩之前的数据,然后复制到本地用测试(直接copy的controller/server.js里面一模一样的代码)pako压缩后数据居然和我正常后端收到的数据不一样
②每次点击一个cell,会发送两次相同的数据,且是无法解压的数据(见①)

我后端是nodejs+koa2+ws搭建的

难道只能用你们的那个springboot弄的server?

**Comment by lxhlxh520** [comment]
已经解决了,将luckysheet的pako升级到最新版重新build即可解决,官方能不能走点心啊,还是这个项目彻底摆烂了?

**Comment by klsqmadi** [comment]
> 已经解决了,将luckysheet的pako升级到最新版重新build即可解决,官方能不能走点心啊,还是这个项目彻底摆烂了?

感谢，非常有用，差点要去改源码把pako压缩去掉了
