### ISSUE TITLE
请教一下添加自定义工具栏，图标怎么引入呢

### ISSUE THREAD

**Issue by care98** [dream-num/Luckysheet#1278]
![30c07a05fbd20b6ac3322a8f4d8ca55](https://user-images.githubusercontent.com/46066901/227877221-d84037c1-a42e-40e1-bd15-47ff82fb7987.png)

顶部工具栏新增了 上传excel功能，但是不知道如何替换掉图标

**Comment by care98** [comment]
> 您好，请问您自定义工具栏按钮的功能是怎么实现的？

您可以参考：https://blog.csdn.net/a519525531/article/details/129064696

**Comment by care98** [comment]
> 您好，请问您自定义工具栏按钮的功能是怎么实现的？

还有这个：https://www.cnblogs.com/daniel-xie/articles/17291845.html
看看能不能帮你解决问题

**Comment by care98** [comment]
> 您好，请问您自定义工具栏按钮的功能是怎么实现的？

还有这个：https://www.cnblogs.com/daniel-xie/articles/17291845.html
看看能不能帮你解决问题

**Comment by zzc-1024** [comment]
这些参考链接很有帮助，十分感谢

> > 您好，请问您自定义工具栏按钮的功能是怎么实现的？
> 
> 还有这个：https://www.cnblogs.com/daniel-xie/articles/17291845.html 看看能不能帮你解决问题
