### ISSUE TITLE
在qiankun微前端框架下，在沙箱模式开启时，无法使用计算公式的功能

### ISSUE THREAD

**Issue by niubishuangjiang** [dream-num/Luckysheet#1294]
### **在源码里看到使用new Function时，window对象并没有指向qiankun子应用的window对象，而是指向了主应用的window对象**
![1681377392028(1)](https://user-images.githubusercontent.com/38605935/231718925-508d4141-3f4a-42f9-9a37-58d4e7d35673.jpg)

**Comment by yanghuanrong** [comment]
这个问题，我并不认为是luckysheet需要去处理的，而是应该在自己的代码中想办法去兼容这个情况，例如修正window对象的指向

**Comment by shijunfeng** [comment]
我也遇到这个问题  请问怎么解决的

**Comment by niubishuangjiang** [comment]
> 我也遇到这个问题 请问怎么解决的

![image](https://github.com/dream-num/Luckysheet/assets/38605935/bfed3d26-82f4-46ab-815f-2878f867a57a)
把方法挂到主应用的window上

**Comment by SmithXiong** [comment]
> > 我也遇到这个问题 请问怎么解决的
> 
> ![image](https://private-user-images.githubusercontent.com/38605935/256735878-bfed3d26-82f4-46ab-815f-2878f867a57a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3Njg4MzAsIm5iZiI6MTcwMTc2ODUzMCwicGF0aCI6Ii8zODYwNTkzNS8yNTY3MzU4NzgtYmZlZDNkMjYtODJmNC00NmFiLTgxNWYtMjg3OGY4NjdhNTdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDA5Mjg1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2NjZkZGQ2YzhmYmUxMWYwNjZjMGIzMjI0MDE4ZWYwOTdlMjJjNzc1Y2ZlMzU1NzNmYWM5NTRhZjdlYmUxYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wxoASoIMh9dni-diCu1Zh7eb3nLxkhyY-ZsiddQyBck) 把方法挂到主应用的window上

这段代码应该写在哪里？引入luckysheet之后吗？

**Comment by yanbin92** [comment]
在qiankun微前端框架下，子应用不引入lunckysheet 由主应用引用，能正常使用 ，  亲测有效。
@niubishuangjiang
