### ISSUE TITLE
execl的隐藏列功能，通过luckysheet解析文件后，再下载的文件，隐藏的列就会显示出来，应该不显示才对的

### ISSUE THREAD

**Issue by niubishuangjiang** [dream-num/Luckysheet#1329]
### execl的隐藏列功能
![1684206638847](https://github.com/dream-num/Luckysheet/assets/38605935/9f186803-d76b-49fa-bff4-65b8483ed380)
### 正常的文件，隐藏了前两列
![image](https://github.com/dream-num/Luckysheet/assets/38605935/1c44d9ca-32e3-44b1-aa94-8a8a7883758c)
### 通过luckysheet解析完后下载，隐藏的列就展示出来了，应该继续隐藏才对
![image](https://github.com/dream-num/Luckysheet/assets/38605935/f36f9f8e-af77-4f8d-a4de-bebff20b7b60)

**Comment by Ming411** [comment]
您好，我也遇到了这个问题，您是怎么解决的呢

**Comment by niubishuangjiang** [comment]
> 您好，我也遇到了这个问题，您是怎么解决的呢

luckysheet.getLuckysheetfile().forEach(function(table) {
    if (table.data.length === 0) return  true
    
    const worksheet = workbook.addWorksheet(table.name)
   
    // 4 隐藏行、列
    for (let key in table.config.colhidden) {
      let colNum = parseInt(key) + 1
      worksheet.getColumn(colNum).hidden = true;
    }
    for (let key in table.config.rowhidden) {
      let rowNum = parseInt(key) + 1
      worksheet.getRow(rowNum).hidden = true;
    }
    return true
  })

**Comment by Ming411** [comment]
非常感谢，问题解决了
