### ISSUE TITLE
[BUG]Merging cells will cause the content to disappear when cells has rich text.

### ISSUE THREAD

**Issue by PIMBA** [dream-num/Luckysheet#133]
**Describe the bug**
Merging cells will cause the content to disappear when cells has rich text

**To Reproduce**
1. Go to https://mengshukeji.github.io/LuckysheetDemo/
2. Copy content from sheet[0] cell[5][0] to sheet[0] cell[6][0]
3. Merge two cells
4. Cell has no content.

**What is expected?**
Expect cell[5][0] content shown in merged cell.

**Screenshots or demo**
If applicable, add screenshots or online demo to help explain your problem.We will be more accurate when we retest.
![image](https://user-images.githubusercontent.com/7321731/97400787-ac010180-192a-11eb-8140-7f24b3d23f79.png)
![image](https://user-images.githubusercontent.com/7321731/97400816-b6bb9680-192a-11eb-84d0-6c0b57926006.png)

**Environment**
 - OS: MacOS
 - Browser Version: [Chrome Version  86.0.4240.80 (Official Build) (64-bit)]
 - Luckysheet Version: [latest]

**Comment by PIMBA** [comment]
any news?

**Comment by Dushusir** [comment]
fixed in update
