### ISSUE TITLE
[BUG]在iframe中使用luckysheet单元格会出现[object Object]

### ISSUE THREAD

**Issue by yiwasheng** [dream-num/Luckysheet#1334]
**描述错误**
因为luckysheet单实例的问题，很多用户选择使用iframe隔离，代码里面使用了 cell instanceof Object，从外部传入iframe，对象不是继承自ifrmae里面的Object，判断为false，从而没有取cell.v，直接cell.toString()取到的值为[object Object]
![image](https://github.com/dream-num/Luckysheet/assets/57080142/66c2e340-b057-4363-9202-bf1750d3342c)
![image](https://github.com/dream-num/Luckysheet/assets/57080142/adb5f4dc-48fe-4406-a770-e1b27bc49301)

**重现**

1. 第一步操作: 创建iframe取出iframe里面的luckusheet
2. 第二步操作: 执行luckysheet.create并传入数据 例: { data: [{ celldata: [{ r: 0, c: 0, v: { v: '测试文字', tb: 2 }}] }]}
3. 最后看到了什么错误: A1单元格显示[object Object]

**期望的结果**
正确显示文字而不是[object Object]
使用src/utils/utils.js 下的getObjType获取类型而不是instanceof

**环境：**
  - 操作系统：Windows
  - 浏览器 版本号：Chrome/113.0.0.0
  - Luckysheet版本：当前仓库master

**Comment by yiwasheng** [comment]
我自己的问题，可以覆盖iframe的Object

**Comment by DONGNEZHA** [comment]
感觉这种直接覆盖Object的方法存在风险，还有其他的办法么
