### ISSUE TITLE
[BUG]发现了个bug vue3弹窗内引入图表导致整个项目element plus样式错乱 急急急！

### ISSUE THREAD

**Issue by lichencc** [dream-num/Luckysheet#1421]
**描述错误**
vue3+vite4+element plus的项目，在某个弹窗内挂在了luckysheet并且使用了图表，关闭弹窗后发现element plus的样式受到了影响，出现了错乱，浏览器刷新后恢复正常，打开弹窗再次异常

**重现**

**期望的结果**
关闭弹窗图表销毁，样式不受影响

**屏幕截图或演示**
正常：
<img width="400" alt="image" src="https://github.com/dream-num/Luckysheet/assets/101000413/8b9869f1-ae1d-4b9e-8f68-a454f7f0c25a">
挂载图表后：
<img width="920" alt="image" src="https://github.com/dream-num/Luckysheet/assets/101000413/240ab136-c756-4653-bf8f-33da90dffdbc">

**环境：**
  - 操作系统：Windows
  - 浏览器 版本号：chrome 116
  - Luckysheet版本：最新版本

**备注**
luckysheet是通过把拉取代码npm run build 后dist下所有的文件放入项目引入的，在element plus的dialog弹窗关闭时也调用了api 
 .destroy（）进行了销毁

**Comment by PayneZC** [comment]
请问！问题是解决了么，如何处理的，我遇到了同样的问题。在配置中，只要使用了chart插件后，created时，同页的表单和按钮等组件的样式都会出问题。

**Comment by lichencc** [comment]
解决了 源码的图表里  luckysheet内部又引入了element UI的cdn，可以考虑屏蔽掉这个cdn引入 或者换成elementPlus 这是我的猜想，我没有试，因为我们的项目暂时不需要chart图表

**Comment by PayneZC** [comment]
ok，非常感谢
