### ISSUE TITLE
[BUG] 取消合并单元格出现的数据联动的问题

### ISSUE THREAD

**Issue by pengyonglei** [dream-num/Luckysheet#147]
![image](https://user-images.githubusercontent.com/11027128/100981398-b9d92080-3581-11eb-8485-6fa74d166afc.png)

![image](https://user-images.githubusercontent.com/11027128/100981514-dffec080-3581-11eb-8e8d-540d16bb20f2.png)

合并单元格取消合并之后, 出现数据联动的问题了.

**Comment by pengyonglei** [comment]
@mengshukeji 请问这个问题可以早一点修复吗 ?  谢谢啦

**Comment by Dushusir** [comment]
已经在更新中修复
fixed in update
