### ISSUE TITLE
[BUG]非全屏模式下，如果页面有滚动条。当表格未聚焦时，单击或者双击表格单元格时，整个页面会滚动到顶部。

### ISSUE THREAD

**Issue by lyf1995** [dream-num/Luckysheet#152]

**Comment by lyf1995** [comment]
![初始](https://user-images.githubusercontent.com/29793465/97833135-9cf5c700-1d0f-11eb-8995-b55e3701e203.png)

**Comment by Mr-xzq** [comment]
我也遇见这个问题了，不知道这个咋解决

**Comment by Mr-xzq** [comment]
#794 我在这边提了个解决方案，不知道你能不能用，可以尝试一下

**Comment by Dushusir** [comment]
fixed in https://github.com/dream-num/Luckysheet/blob/842089b7703bc5dab42930eb1fb0dc7ac220fd33/src/utils/util.js#L502
