### ISSUE TITLE
[BUG] IE11 无法运行

### ISSUE THREAD

**Issue by cdswyda** [dream-num/Luckysheet#637]
**描述错误**
如题， IE 11 下无法运行。

**重现**
重现错误的步骤：
使用 IE 11 访问demo， demo页面无法加载。

**期望的结果**
看gulp的构建，应该是支持IE11的才对。

**屏幕截图或演示**
![image](https://user-images.githubusercontent.com/13060680/117404333-5a21df80-af3c-11eb-99d7-9d3aec9bab63.png)

**排查**

这里本地进行构建，错误主要是 `flatpickr` 这个库导致的， `4.6.6` 及其以后的版本均存在问题。其 package 中多了 module 指向 esm  的版本，这里面未经过babel处理。

修改构建脚本，将 `exclude: 'node_modules/**'` 改为 `/node_modules\/(?!(flatpickr)\/)/` 将 flatpickr 也进行babel处理。

仍未解决问题

![image](https://user-images.githubusercontent.com/13060680/117405068-9e61af80-af3d-11eb-93bc-674fc1e1f88f.png)

此时是 `Proxy` 导致 https://github.com/mengshukeji/Luckysheet/blob/9a8cb551a7bfc045023650bee912f861b5cfef33/src/utils/util.js#L825-L837

看记录是 2020.12.20 https://github.com/mengshukeji/Luckysheet/commit/215dec27d796ee9b5be7857a425093a53db84332 新增了 `Proxy`

但是此提交的前一天的issue和pr (2020.12.19) https://github.com/mengshukeji/Luckysheet/issues/234 还是修复了 IE 11 demo 的支持的。

此处有无解决方案?   `Proxy` 无法被转换，是否存在其他实现方式？

**Comment by nikylin** [comment]
我发现工程用到的flatpickr版本是4.6.9(没有处理es6语法)，4.6.10修复了，所以我直接升级到了最新版(4.6.10)，然后打包方式恢复成rollup打包，亲测可以在IE上正常查看demo,就是面上的一些基本功能验了一下，可以正常显示操作。具体改动地方：
1.flatpickr版本升级>=4.6.10
2./src/index.js  需要把`module.exports =  luckysheet` 改成 `window.luckysheet = luckysheet;export default luckysheet;`
3.gulpfile.js 把core方法注释掉，把core_rollup改成core就可以了
4.src/index.html 箭头函数ie 不支持，这边是没转的，我是给他注释掉
