### ISSUE TITLE
[Feature request]建议将项目中的iconfont改为其他名称

### ISSUE THREAD

**Issue by zsedcbm** [dream-num/Luckysheet#645]
**您的功能请求与问题有关吗？**
当项目集成多个包含iconfont的项目时，往往会彼此互相冲突，到此图标无法正常显示。

**描述您想要的解决方案**
建议将项目中的iconfont改为当前项目独有的一个名称

**Comment by 65min** [comment]
能否将luckysheet的iconfont图标库的font family改为其他，不要用默认的“iconfont”？

**Comment by morningsun42** [comment]
支持，作为插件，iconfont这个名字很容易和主项目冲突

**Comment by libbGit** [comment]
完全支持，系统项目组可以修改下
