### ISSUE TITLE
遍历 中添加公式  初始化使用问题

### ISSUE THREAD

**Issue by linzhixiang** [dream-num/Luckysheet#803]
我这边循环生产数据时，同时把公式也循环生成了比如 SUM(E6+F6)，但是展示时，需要手动改E6 或者 F6，G6的公式才会计算...这个不会自动计算吗
![1](https://user-images.githubusercontent.com/20457072/137828374-53ea98c6-7d29-4445-a132-f3d8ab97029c.png)
![2](https://user-images.githubusercontent.com/20457072/137828384-d100d052-4a87-45cb-9dfb-7cd5af76f2ed.png)

**Comment by oirobot-github** [comment]
> 

怎么手动调用啊
