### ISSUE TITLE
导入单元格比较多的excel文件渲染超级慢，[BUG]发现了个bug

### ISSUE THREAD

**Issue by Lousihu** [dream-num/Luckysheet#809]
导入单元格比较多的excel文件时，渲染超级慢，甚至浏览器会崩溃
**描述错误**

导入

**重现**

1. 第一步操作:
2. 第二步操作:
3. 第三步操作:
4. 最后看到了什么错误:

**期望的结果**

**屏幕截图或演示**

**环境：**
  - 操作系统：Mac
  - 浏览器 版本号：Chrome 版本 88.0.4324.182
  - Luckysheet版本：2.1.13

**备注**

针对这个问题，我也进行了优化，后续会贴出优化的代码

**Comment by zhangxiaohui** [comment]
也遇到相同问题了，请教一下怎么解决的
